// themes.js - 50 Unique Premium Themes
export const themes = {
  // DARK THEMES (1-10)
  midnight: {
    name: 'Midnight Elite',
    bg: 'bg-gray-950',
    card: 'bg-gray-900',
    cardHover: 'hover:bg-gray-800',
    text: 'text-white',
    textSecondary: 'text-gray-300',
    border: 'border-gray-800',
    primary: 'bg-indigo-600',
    primaryHover: 'hover:bg-indigo-700',
    accent: 'from-indigo-600 to-purple-600',
    gradient: 'bg-gradient-to-br from-gray-950 to-gray-900',
    shadow: 'shadow-2xl shadow-indigo-500/10'
  },
  charcoal: {
    name: 'Charcoal Pro',
    bg: 'bg-neutral-900',
    card: 'bg-neutral-800',
    cardHover: 'hover:bg-neutral-700',
    text: 'text-neutral-100',
    textSecondary: 'text-neutral-400',
    border: 'border-neutral-700',
    primary: 'bg-amber-500',
    primaryHover: 'hover:bg-amber-600',
    accent: 'from-amber-500 to-orange-500',
    gradient: 'bg-gradient-to-br from-neutral-900 to-neutral-800',
    shadow: 'shadow-2xl shadow-amber-500/10'
  },
  obsidian: {
    name: 'Obsidian Black',
    bg: 'bg-black',
    card: 'bg-zinc-900',
    cardHover: 'hover:bg-zinc-800',
    text: 'text-zinc-100',
    textSecondary: 'text-zinc-400',
    border: 'border-zinc-800',
    primary: 'bg-emerald-500',
    primaryHover: 'hover:bg-emerald-600',
    accent: 'from-emerald-500 to-teal-500',
    gradient: 'bg-gradient-to-br from-black to-zinc-900',
    shadow: 'shadow-2xl shadow-emerald-500/10'
  },
  darkGalaxy: {
    name: 'Dark Galaxy',
    bg: 'bg-[#0B0C10]',
    card: 'bg-[#1F2833]',
    cardHover: 'hover:bg-[#2C3A4A]',
    text: 'text-[#45A29E]',
    textSecondary: 'text-[#C5C6C7]',
    border: 'border-[#45A29E]/30',
    primary: 'bg-[#66FCF1]',
    primaryHover: 'hover:bg-[#45A29E]',
    accent: 'from-[#66FCF1] to-[#45A29E]',
    gradient: 'bg-gradient-to-br from-[#0B0C10] to-[#1F2833]',
    shadow: 'shadow-2xl shadow-[#45A29E]/20'
  },
  vampire: {
    name: 'Vampire Night',
    bg: 'bg-[#1a0b0b]',
    card: 'bg-[#2d1a1a]',
    cardHover: 'hover:bg-[#3d2626]',
    text: 'text-[#ff6b6b]',
    textSecondary: 'text-[#ffb8b8]',
    border: 'border-red-900',
    primary: 'bg-red-600',
    primaryHover: 'hover:bg-red-700',
    accent: 'from-red-600 to-rose-600',
    gradient: 'bg-gradient-to-br from-[#1a0b0b] to-[#2d1a1a]',
    shadow: 'shadow-2xl shadow-red-900/30'
  },
  deepOcean: {
    name: 'Deep Ocean',
    bg: 'bg-[#0a192f]',
    card: 'bg-[#112240]',
    cardHover: 'hover:bg-[#1a3650]',
    text: 'text-[#64ffda]',
    textSecondary: 'text-[#8892b0]',
    border: 'border-[#233554]',
    primary: 'bg-[#64ffda]',
    primaryHover: 'hover:bg-[#4cd8b5]',
    accent: 'from-[#64ffda] to-[#4cd8b5]',
    gradient: 'bg-gradient-to-br from-[#0a192f] to-[#112240]',
    shadow: 'shadow-2xl shadow-[#64ffda]/20'
  },
  matteBlack: {
    name: 'Matte Black',
    bg: 'bg-[#121212]',
    card: 'bg-[#1E1E1E]',
    cardHover: 'hover:bg-[#2D2D2D]',
    text: 'text-[#E0E0E0]',
    textSecondary: 'text-[#A0A0A0]',
    border: 'border-[#333333]',
    primary: 'bg-[#BB86FC]',
    primaryHover: 'hover:bg-[#9966CC]',
    accent: 'from-[#BB86FC] to-[#03DAC6]',
    gradient: 'bg-gradient-to-br from-[#121212] to-[#1E1E1E]',
    shadow: 'shadow-2xl shadow-purple-900/30'
  },
  nightRider: {
    name: 'Night Rider',
    bg: 'bg-[#0F0F0F]',
    card: 'bg-[#1A1A1A]',
    cardHover: 'hover:bg-[#252525]',
    text: 'text-[#FFFFFF]',
    textSecondary: 'text-[#B0B0B0]',
    border: 'border-[#2A2A2A]',
    primary: 'bg-[#FF4444]',
    primaryHover: 'hover:bg-[#CC0000]',
    accent: 'from-[#FF4444] to-[#FF8800]',
    gradient: 'bg-gradient-to-br from-[#0F0F0F] to-[#1A1A1A]',
    shadow: 'shadow-2xl shadow-red-900/30'
  },
  storm: {
    name: 'Storm Cloud',
    bg: 'bg-[#1a202c]',
    card: 'bg-[#2d3748]',
    cardHover: 'hover:bg-[#374151]',
    text: 'text-[#e2e8f0]',
    textSecondary: 'text-[#a0aec0]',
    border: 'border-[#4a5568]',
    primary: 'bg-[#4299e1]',
    primaryHover: 'hover:bg-[#3182ce]',
    accent: 'from-[#4299e1] to-[#9f7aea]',
    gradient: 'bg-gradient-to-br from-[#1a202c] to-[#2d3748]',
    shadow: 'shadow-2xl shadow-blue-900/30'
  },
  espresso: {
    name: 'Espresso',
    bg: 'bg-[#2C1810]',
    card: 'bg-[#3E2723]',
    cardHover: 'hover:bg-[#4E342E]',
    text: 'text-[#D7CCC8]',
    textSecondary: 'text-[#BCAAA4]',
    border: 'border-[#5D4037]',
    primary: 'bg-[#FF9800]',
    primaryHover: 'hover:bg-[#F57C00]',
    accent: 'from-[#FF9800] to-[#FF5722]',
    gradient: 'bg-gradient-to-br from-[#2C1810] to-[#3E2723]',
    shadow: 'shadow-2xl shadow-orange-900/30'
  },

  // VIBRANT GRADIENT THEMES (11-20)
  sunsetBlaze: {
    name: 'Sunset Blaze',
    bg: 'bg-gradient-to-br from-orange-600 via-red-600 to-pink-600',
    card: 'bg-white/10 backdrop-blur-lg',
    cardHover: 'hover:bg-white/20',
    text: 'text-white',
    textSecondary: 'text-orange-100',
    border: 'border-white/20',
    primary: 'bg-yellow-500',
    primaryHover: 'hover:bg-yellow-600',
    accent: 'from-yellow-500 to-orange-500',
    gradient: 'bg-gradient-to-br from-orange-600 via-red-600 to-pink-600',
    shadow: 'shadow-2xl shadow-orange-500/30'
  },
  oceanDeep: {
    name: 'Ocean Deep',
    bg: 'bg-gradient-to-br from-blue-900 via-cyan-800 to-teal-900',
    card: 'bg-white/10 backdrop-blur-lg',
    cardHover: 'hover:bg-white/20',
    text: 'text-white',
    textSecondary: 'text-cyan-100',
    border: 'border-white/20',
    primary: 'bg-cyan-400',
    primaryHover: 'hover:bg-cyan-500',
    accent: 'from-cyan-400 to-blue-500',
    gradient: 'bg-gradient-to-br from-blue-900 via-cyan-800 to-teal-900',
    shadow: 'shadow-2xl shadow-cyan-500/30'
  },
  forestMagic: {
    name: 'Forest Magic',
    bg: 'bg-gradient-to-br from-emerald-900 via-green-800 to-lime-900',
    card: 'bg-white/10 backdrop-blur-lg',
    cardHover: 'hover:bg-white/20',
    text: 'text-white',
    textSecondary: 'text-emerald-100',
    border: 'border-white/20',
    primary: 'bg-lime-500',
    primaryHover: 'hover:bg-lime-600',
    accent: 'from-lime-500 to-emerald-500',
    gradient: 'bg-gradient-to-br from-emerald-900 via-green-800 to-lime-900',
    shadow: 'shadow-2xl shadow-emerald-500/30'
  },
  aurora: {
    name: 'Aurora',
    bg: 'bg-gradient-to-r from-purple-900 via-pink-800 to-blue-900',
    card: 'bg-white/10 backdrop-blur-xl',
    cardHover: 'hover:bg-white/20',
    text: 'text-white',
    textSecondary: 'text-purple-100',
    border: 'border-white/30',
    primary: 'bg-pink-500',
    primaryHover: 'hover:bg-pink-600',
    accent: 'from-pink-500 to-purple-500',
    gradient: 'bg-gradient-to-r from-purple-900 via-pink-800 to-blue-900',
    shadow: 'shadow-2xl shadow-purple-500/40'
  },
  tropical: {
    name: 'Tropical',
    bg: 'bg-gradient-to-br from-yellow-500 via-orange-500 to-red-500',
    card: 'bg-white/20 backdrop-blur-lg',
    cardHover: 'hover:bg-white/30',
    text: 'text-white',
    textSecondary: 'text-yellow-50',
    border: 'border-white/30',
    primary: 'bg-orange-400',
    primaryHover: 'hover:bg-orange-500',
    accent: 'from-orange-400 to-yellow-400',
    gradient: 'bg-gradient-to-br from-yellow-500 via-orange-500 to-red-500',
    shadow: 'shadow-2xl shadow-orange-500/30'
  },
  neonCyber: {
    name: 'Neon Cyber',
    bg: 'bg-gradient-to-br from-black via-purple-900 to-pink-800',
    card: 'bg-black/50 backdrop-blur-xl border-2',
    cardHover: 'hover:bg-black/70',
    text: 'text-[#00ff00]',
    textSecondary: 'text-[#ff00ff]',
    border: 'border-[#00ff00]',
    primary: 'bg-[#ff00ff]',
    primaryHover: 'hover:bg-[#cc00cc]',
    accent: 'from-[#00ff00] to-[#ff00ff]',
    gradient: 'bg-gradient-to-br from-black via-purple-900 to-pink-800',
    shadow: 'shadow-2xl shadow-[#ff00ff]/50'
  },
  candyCrush: {
    name: 'Candy Crush',
    bg: 'bg-gradient-to-br from-pink-400 via-purple-400 to-blue-400',
    card: 'bg-white/20 backdrop-blur-md',
    cardHover: 'hover:bg-white/30',
    text: 'text-purple-900',
    textSecondary: 'text-purple-700',
    border: 'border-white/40',
    primary: 'bg-pink-500',
    primaryHover: 'hover:bg-pink-600',
    accent: 'from-pink-500 to-purple-500',
    gradient: 'bg-gradient-to-br from-pink-400 via-purple-400 to-blue-400',
    shadow: 'shadow-2xl shadow-pink-500/30'
  },
  fireIce: {
    name: 'Fire & Ice',
    bg: 'bg-gradient-to-r from-red-600 via-orange-500 to-blue-600',
    card: 'bg-white/10 backdrop-blur-lg',
    cardHover: 'hover:bg-white/20',
    text: 'text-white',
    textSecondary: 'text-orange-100',
    border: 'border-white/20',
    primary: 'bg-cyan-400',
    primaryHover: 'hover:bg-cyan-500',
    accent: 'from-red-500 to-cyan-500',
    gradient: 'bg-gradient-to-r from-red-600 via-orange-500 to-blue-600',
    shadow: 'shadow-2xl shadow-red-500/30'
  },
  royalPurple: {
    name: 'Royal Purple',
    bg: 'bg-gradient-to-br from-purple-800 via-indigo-900 to-purple-900',
    card: 'bg-purple-900/50 backdrop-blur-lg',
    cardHover: 'hover:bg-purple-800/60',
    text: 'text-purple-100',
    textSecondary: 'text-purple-200',
    border: 'border-purple-700',
    primary: 'bg-indigo-500',
    primaryHover: 'hover:bg-indigo-600',
    accent: 'from-indigo-500 to-purple-500',
    gradient: 'bg-gradient-to-br from-purple-800 via-indigo-900 to-purple-900',
    shadow: 'shadow-2xl shadow-purple-500/30'
  },
  goldenHour: {
    name: 'Golden Hour',
    bg: 'bg-gradient-to-br from-amber-700 via-yellow-600 to-orange-700',
    card: 'bg-amber-900/50 backdrop-blur-lg',
    cardHover: 'hover:bg-amber-800/60',
    text: 'text-yellow-100',
    textSecondary: 'text-yellow-200',
    border: 'border-yellow-700',
    primary: 'bg-amber-500',
    primaryHover: 'hover:bg-amber-600',
    accent: 'from-amber-500 to-yellow-500',
    gradient: 'bg-gradient-to-br from-amber-700 via-yellow-600 to-orange-700',
    shadow: 'shadow-2xl shadow-amber-500/30'
  },

  // GLASSMORPHISM THEMES (21-30)
  glassPremium: {
    name: 'Glass Premium',
    bg: 'bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900',
    card: 'bg-white/5 backdrop-blur-xl',
    cardHover: 'hover:bg-white/10',
    text: 'text-white',
    textSecondary: 'text-gray-300',
    border: 'border-white/10',
    primary: 'bg-gradient-to-r from-blue-500 to-purple-600',
    primaryHover: 'hover:from-blue-600 hover:to-purple-700',
    accent: 'from-blue-500 to-purple-600',
    gradient: 'bg-gradient-to-br from-gray-900 to-gray-800',
    shadow: 'shadow-2xl shadow-white/10'
  },
  frostGlass: {
    name: 'Frost Glass',
    bg: 'bg-gradient-to-br from-blue-50 to-indigo-100',
    card: 'bg-white/40 backdrop-blur-md',
    cardHover: 'hover:bg-white/50',
    text: 'text-gray-800',
    textSecondary: 'text-gray-600',
    border: 'border-white/50',
    primary: 'bg-indigo-600',
    primaryHover: 'hover:bg-indigo-700',
    accent: 'from-indigo-600 to-blue-600',
    gradient: 'bg-gradient-to-br from-blue-50 to-indigo-100',
    shadow: 'shadow-xl shadow-indigo-500/20'
  },
  crystal: {
    name: 'Crystal Clear',
    bg: 'bg-gradient-to-br from-teal-100 to-cyan-100',
    card: 'bg-white/30 backdrop-blur-md',
    cardHover: 'hover:bg-white/40',
    text: 'text-teal-900',
    textSecondary: 'text-teal-700',
    border: 'border-white/40',
    primary: 'bg-teal-600',
    primaryHover: 'hover:bg-teal-700',
    accent: 'from-teal-600 to-cyan-600',
    gradient: 'bg-gradient-to-br from-teal-100 to-cyan-100',
    shadow: 'shadow-lg shadow-teal-500/20'
  },
  diamond: {
    name: 'Diamond Luxe',
    bg: 'bg-gradient-to-br from-slate-100 to-gray-200',
    card: 'bg-white/60 backdrop-blur-lg',
    cardHover: 'hover:bg-white/70',
    text: 'text-slate-900',
    textSecondary: 'text-slate-700',
    border: 'border-white/80',
    primary: 'bg-slate-800',
    primaryHover: 'hover:bg-slate-900',
    accent: 'from-slate-800 to-gray-800',
    gradient: 'bg-gradient-to-br from-slate-100 to-gray-200',
    shadow: 'shadow-xl shadow-slate-500/20'
  },
  pearl: {
    name: 'Pearl White',
    bg: 'bg-gradient-to-br from-white to-gray-100',
    card: 'bg-white/80 backdrop-blur-md',
    cardHover: 'hover:bg-white/90',
    text: 'text-gray-900',
    textSecondary: 'text-gray-600',
    border: 'border-gray-200',
    primary: 'bg-rose-500',
    primaryHover: 'hover:bg-rose-600',
    accent: 'from-rose-500 to-pink-500',
    gradient: 'bg-gradient-to-br from-white to-gray-100',
    shadow: 'shadow-xl shadow-gray-500/20'
  },
  arcticGlass: {
    name: 'Arctic Glass',
    bg: 'bg-gradient-to-br from-cyan-50 to-blue-100',
    card: 'bg-white/50 backdrop-blur-lg',
    cardHover: 'hover:bg-white/60',
    text: 'text-cyan-900',
    textSecondary: 'text-cyan-700',
    border: 'border-white/60',
    primary: 'bg-cyan-600',
    primaryHover: 'hover:bg-cyan-700',
    accent: 'from-cyan-600 to-blue-600',
    gradient: 'bg-gradient-to-br from-cyan-50 to-blue-100',
    shadow: 'shadow-lg shadow-cyan-500/20'
  },
  mysticGlass: {
    name: 'Mystic Glass',
    bg: 'bg-gradient-to-br from-purple-100 to-pink-100',
    card: 'bg-white/40 backdrop-blur-xl',
    cardHover: 'hover:bg-white/50',
    text: 'text-purple-900',
    textSecondary: 'text-purple-700',
    border: 'border-white/50',
    primary: 'bg-purple-600',
    primaryHover: 'hover:bg-purple-700',
    accent: 'from-purple-600 to-pink-600',
    gradient: 'bg-gradient-to-br from-purple-100 to-pink-100',
    shadow: 'shadow-xl shadow-purple-500/20'
  },
  emeraldGlass: {
    name: 'Emerald Glass',
    bg: 'bg-gradient-to-br from-emerald-50 to-green-100',
    card: 'bg-white/40 backdrop-blur-lg',
    cardHover: 'hover:bg-white/50',
    text: 'text-emerald-900',
    textSecondary: 'text-emerald-700',
    border: 'border-white/50',
    primary: 'bg-emerald-600',
    primaryHover: 'hover:bg-emerald-700',
    accent: 'from-emerald-600 to-teal-600',
    gradient: 'bg-gradient-to-br from-emerald-50 to-green-100',
    shadow: 'shadow-lg shadow-emerald-500/20'
  },
  sapphireGlass: {
    name: 'Sapphire Glass',
    bg: 'bg-gradient-to-br from-blue-100 to-indigo-200',
    card: 'bg-white/30 backdrop-blur-md',
    cardHover: 'hover:bg-white/40',
    text: 'text-blue-900',
    textSecondary: 'text-blue-700',
    border: 'border-white/40',
    primary: 'bg-blue-600',
    primaryHover: 'hover:bg-blue-700',
    accent: 'from-blue-600 to-indigo-600',
    gradient: 'bg-gradient-to-br from-blue-100 to-indigo-200',
    shadow: 'shadow-xl shadow-blue-500/20'
  },
  amberGlass: {
    name: 'Amber Glass',
    bg: 'bg-gradient-to-br from-amber-50 to-orange-100',
    card: 'bg-white/40 backdrop-blur-lg',
    cardHover: 'hover:bg-white/50',
    text: 'text-amber-900',
    textSecondary: 'text-amber-700',
    border: 'border-white/50',
    primary: 'bg-amber-600',
    primaryHover: 'hover:bg-amber-700',
    accent: 'from-amber-600 to-orange-600',
    gradient: 'bg-gradient-to-br from-amber-50 to-orange-100',
    shadow: 'shadow-lg shadow-amber-500/20'
  },

  // NEUMORPHISM THEMES (31-35)
  neumorphLight: {
    name: 'Neumorph Light',
    bg: 'bg-[#e0e0e0]',
    card: 'bg-[#e0e0e0] shadow-[20px_20px_60px_#bebebe,-20px_-20px_60px_#ffffff]',
    cardHover: 'hover:shadow-[inset_20px_20px_60px_#bebebe,inset_-20px_-20px_60px_#ffffff]',
    text: 'text-gray-800',
    textSecondary: 'text-gray-600',
    border: 'border-gray-300',
    primary: 'bg-[#e0e0e0] shadow-[5px_5px_15px_#bebebe,-5px_-5px_15px_#ffffff]',
    primaryHover: 'hover:shadow-[inset_5px_5px_15px_#bebebe,inset_-5px_-5px_15px_#ffffff]',
    accent: 'from-gray-600 to-gray-800',
    gradient: 'bg-[#e0e0e0]',
    shadow: 'shadow-2xl'
  },
  neumorphDark: {
    name: 'Neumorph Dark',
    bg: 'bg-[#1a1a1a]',
    card: 'bg-[#1a1a1a] shadow-[20px_20px_60px_#121212,-20px_-20px_60px_#222222]',
    cardHover: 'hover:shadow-[inset_20px_20px_60px_#121212,inset_-20px_-20px_60px_#222222]',
    text: 'text-gray-100',
    textSecondary: 'text-gray-400',
    border: 'border-gray-700',
    primary: 'bg-[#1a1a1a] shadow-[5px_5px_15px_#121212,-5px_-5px_15px_#222222]',
    primaryHover: 'hover:shadow-[inset_5px_5px_15px_#121212,inset_-5px_-5px_15px_#222222]',
    accent: 'from-gray-400 to-gray-200',
    gradient: 'bg-[#1a1a1a]',
    shadow: 'shadow-2xl'
  },
  neumorphBlue: {
    name: 'Neumorph Blue',
    bg: 'bg-[#c8d8e8]',
    card: 'bg-[#c8d8e8] shadow-[20px_20px_60px_#aab8c5,-20px_-20px_60px_#e6f8ff]',
    cardHover: 'hover:shadow-[inset_20px_20px_60px_#aab8c5,inset_-20px_-20px_60px_#e6f8ff]',
    text: 'text-blue-900',
    textSecondary: 'text-blue-700',
    border: 'border-blue-300',
    primary: 'bg-[#c8d8e8] shadow-[5px_5px_15px_#aab8c5,-5px_-5px_15px_#e6f8ff]',
    primaryHover: 'hover:shadow-[inset_5px_5px_15px_#aab8c5,inset_-5px_-5px_15px_#e6f8ff]',
    accent: 'from-blue-700 to-blue-900',
    gradient: 'bg-[#c8d8e8]',
    shadow: 'shadow-2xl'
  },
  neumorphPink: {
    name: 'Neumorph Pink',
    bg: 'bg-[#f0e0e8]',
    card: 'bg-[#f0e0e8] shadow-[20px_20px_60px_#ccbec5,-20px_-20px_60px_#ffffff]',
    cardHover: 'hover:shadow-[inset_20px_20px_60px_#ccbec5,inset_-20px_-20px_60px_#ffffff]',
    text: 'text-pink-900',
    textSecondary: 'text-pink-700',
    border: 'border-pink-300',
    primary: 'bg-[#f0e0e8] shadow-[5px_5px_15px_#ccbec5,-5px_-5px_15px_#ffffff]',
    primaryHover: 'hover:shadow-[inset_5px_5px_15px_#ccbec5,inset_-5px_-5px_15px_#ffffff]',
    accent: 'from-pink-700 to-rose-700',
    gradient: 'bg-[#f0e0e8]',
    shadow: 'shadow-2xl'
  },
  neumorphGreen: {
    name: 'Neumorph Green',
    bg: 'bg-[#d4e8d4]',
    card: 'bg-[#d4e8d4] shadow-[20px_20px_60px_#b4c5b4,-20px_-20px_60px_#f4fff4]',
    cardHover: 'hover:shadow-[inset_20px_20px_60px_#b4c5b4,inset_-20px_-20px_60px_#f4fff4]',
    text: 'text-green-900',
    textSecondary: 'text-green-700',
    border: 'border-green-300',
    primary: 'bg-[#d4e8d4] shadow-[5px_5px_15px_#b4c5b4,-5px_-5px_15px_#f4fff4]',
    primaryHover: 'hover:shadow-[inset_5px_5px_15px_#b4c5b4,inset_-5px_-5px_15px_#f4fff4]',
    accent: 'from-green-700 to-emerald-700',
    gradient: 'bg-[#d4e8d4]',
    shadow: 'shadow-2xl'
  },

  // PASTEL THEMES (36-40)
  pastelDream: {
    name: 'Pastel Dream',
    bg: 'bg-gradient-to-br from-pink-200 via-purple-200 to-blue-200',
    card: 'bg-white/60 backdrop-blur-sm',
    cardHover: 'hover:bg-white/70',
    text: 'text-gray-800',
    textSecondary: 'text-gray-600',
    border: 'border-white/50',
    primary: 'bg-pink-400',
    primaryHover: 'hover:bg-pink-500',
    accent: 'from-pink-400 to-purple-400',
    gradient: 'bg-gradient-to-br from-pink-200 via-purple-200 to-blue-200',
    shadow: 'shadow-xl shadow-pink-500/20'
  },
  mintFresh: {
    name: 'Mint Fresh',
    bg: 'bg-gradient-to-br from-mint-200 to-teal-200',
    card: 'bg-white/70 backdrop-blur-sm',
    cardHover: 'hover:bg-white/80',
    text: 'text-teal-900',
    textSecondary: 'text-teal-700',
    border: 'border-white/50',
    primary: 'bg-teal-500',
    primaryHover: 'hover:bg-teal-600',
    accent: 'from-teal-500 to-mint-500',
    gradient: 'bg-gradient-to-br from-[#a8e6cf] to-[#d4f1f9]',
    shadow: 'shadow-xl shadow-teal-500/20'
  },
  lavender: {
    name: 'Lavender Field',
    bg: 'bg-gradient-to-br from-purple-200 to-indigo-200',
    card: 'bg-white/60 backdrop-blur-sm',
    cardHover: 'hover:bg-white/70',
    text: 'text-purple-900',
    textSecondary: 'text-purple-700',
    border: 'border-white/50',
    primary: 'bg-purple-500',
    primaryHover: 'hover:bg-purple-600',
    accent: 'from-purple-500 to-indigo-500',
    gradient: 'bg-gradient-to-br from-purple-200 to-indigo-200',
    shadow: 'shadow-xl shadow-purple-500/20'
  },
  peachBlush: {
    name: 'Peach Blush',
    bg: 'bg-gradient-to-br from-orange-200 to-pink-200',
    card: 'bg-white/60 backdrop-blur-sm',
    cardHover: 'hover:bg-white/70',
    text: 'text-orange-900',
    textSecondary: 'text-orange-700',
    border: 'border-white/50',
    primary: 'bg-orange-500',
    primaryHover: 'hover:bg-orange-600',
    accent: 'from-orange-500 to-pink-500',
    gradient: 'bg-gradient-to-br from-orange-200 to-pink-200',
    shadow: 'shadow-xl shadow-orange-500/20'
  },
  skyBlue: {
    name: 'Sky Blue',
    bg: 'bg-gradient-to-br from-sky-200 to-blue-200',
    card: 'bg-white/70 backdrop-blur-sm',
    cardHover: 'hover:bg-white/80',
    text: 'text-blue-900',
    textSecondary: 'text-blue-700',
    border: 'border-white/50',
    primary: 'bg-blue-500',
    primaryHover: 'hover:bg-blue-600',
    accent: 'from-blue-500 to-sky-500',
    gradient: 'bg-gradient-to-br from-sky-200 to-blue-200',
    shadow: 'shadow-xl shadow-blue-500/20'
  },

  // PREMIUM DARK-LUXURY THEMES (41-45)
  luxuryGold: {
    name: 'Luxury Gold',
    bg: 'bg-gradient-to-br from-gray-900 to-black',
    card: 'bg-gradient-to-br from-gray-800/90 to-gray-900/90 border-2 border-yellow-500/50',
    cardHover: 'hover:border-yellow-500',
    text: 'text-yellow-500',
    textSecondary: 'text-gray-300',
    border: 'border-yellow-500/30',
    primary: 'bg-gradient-to-r from-yellow-500 to-amber-500',
    primaryHover: 'hover:from-yellow-600 hover:to-amber-600',
    accent: 'from-yellow-500 to-amber-500',
    gradient: 'bg-gradient-to-br from-gray-900 to-black',
    shadow: 'shadow-2xl shadow-yellow-500/30'
  },
  platinum: {
    name: 'Platinum',
    bg: 'bg-gradient-to-br from-slate-800 to-gray-900',
    card: 'bg-gradient-to-br from-slate-700/90 to-slate-800/90 border border-gray-400',
    cardHover: 'hover:border-gray-300',
    text: 'text-gray-200',
    textSecondary: 'text-gray-400',
    border: 'border-gray-600',
    primary: 'bg-gradient-to-r from-gray-400 to-gray-500',
    primaryHover: 'hover:from-gray-500 hover:to-gray-600',
    accent: 'from-gray-400 to-gray-600',
    gradient: 'bg-gradient-to-br from-slate-800 to-gray-900',
    shadow: 'shadow-2xl shadow-gray-500/30'
  },
  rubyRed: {
    name: 'Ruby Red',
    bg: 'bg-gradient-to-br from-red-950 to-rose-950',
    card: 'bg-gradient-to-br from-red-900/80 to-rose-900/80 border border-red-500',
    cardHover: 'hover:border-red-400',
    text: 'text-red-400',
    textSecondary: 'text-red-200',
    border: 'border-red-800',
    primary: 'bg-red-600',
    primaryHover: 'hover:bg-red-700',
    accent: 'from-red-600 to-rose-600',
    gradient: 'bg-gradient-to-br from-red-950 to-rose-950',
    shadow: 'shadow-2xl shadow-red-500/30'
  },
  sapphire: {
    name: 'Sapphire',
    bg: 'bg-gradient-to-br from-blue-950 to-indigo-950',
    card: 'bg-gradient-to-br from-blue-900/80 to-indigo-900/80 border border-blue-500',
    cardHover: 'hover:border-blue-400',
    text: 'text-blue-400',
    textSecondary: 'text-blue-200',
    border: 'border-blue-800',
    primary: 'bg-blue-600',
    primaryHover: 'hover:bg-blue-700',
    accent: 'from-blue-600 to-indigo-600',
    gradient: 'bg-gradient-to-br from-blue-950 to-indigo-950',
    shadow: 'shadow-2xl shadow-blue-500/30'
  },
  emeraldLux: {
    name: 'Emerald Lux',
    bg: 'bg-gradient-to-br from-emerald-950 to-green-950',
    card: 'bg-gradient-to-br from-emerald-900/80 to-green-900/80 border border-emerald-500',
    cardHover: 'hover:border-emerald-400',
    text: 'text-emerald-400',
    textSecondary: 'text-emerald-200',
    border: 'border-emerald-800',
    primary: 'bg-emerald-600',
    primaryHover: 'hover:bg-emerald-700',
    accent: 'from-emerald-600 to-green-600',
    gradient: 'bg-gradient-to-br from-emerald-950 to-green-950',
    shadow: 'shadow-2xl shadow-emerald-500/30'
  },

  // HOLOGRAPHIC / SPECIAL (46-50)
  holographic: {
    name: 'Holographic',
    bg: 'bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600',
    card: 'bg-black/50 backdrop-blur-xl border border-white/30',
    cardHover: 'hover:bg-black/60',
    text: 'text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-pink-400 to-blue-400',
    textSecondary: 'text-gray-300',
    border: 'border-white/30',
    primary: 'bg-gradient-to-r from-purple-500 via-pink-500 to-blue-500',
    primaryHover: 'hover:from-purple-600 hover:via-pink-600 hover:to-blue-600',
    accent: 'from-purple-500 via-pink-500 to-blue-500',
    gradient: 'bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600',
    shadow: 'shadow-2xl shadow-purple-500/50'
  },
  rainbow: {
    name: 'Rainbow',
    bg: 'bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 to-purple-500',
    card: 'bg-white/10 backdrop-blur-xl border border-white/30',
    cardHover: 'hover:bg-white/20',
    text: 'text-white',
    textSecondary: 'text-gray-200',
    border: 'border-white/30',
    primary: 'bg-white text-black',
    primaryHover: 'hover:bg-gray-100',
    accent: 'from-red-500 to-purple-500',
    gradient: 'bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 to-purple-500',
    shadow: 'shadow-2xl shadow-white/30'
  },
  cyberpunk: {
    name: 'Cyberpunk 2077',
    bg: 'bg-gradient-to-br from-yellow-300 via-pink-500 to-purple-900',
    card: 'bg-black/70 backdrop-blur-xl border-2 border-cyan-400',
    cardHover: 'hover:border-yellow-400',
    text: 'text-cyan-400',
    textSecondary: 'text-pink-400',
    border: 'border-cyan-500',
    primary: 'bg-yellow-500 text-black',
    primaryHover: 'hover:bg-yellow-400',
    accent: 'from-yellow-500 via-pink-500 to-cyan-500',
    gradient: 'bg-gradient-to-br from-yellow-300 via-pink-500 to-purple-900',
    shadow: 'shadow-2xl shadow-cyan-500/50'
  },
  vaporwave: {
    name: 'Vaporwave',
    bg: 'bg-gradient-to-br from-pink-500 to-purple-900',
    card: 'bg-purple-900/50 backdrop-blur-xl border border-pink-500',
    cardHover: 'hover:bg-purple-800/60',
    text: 'text-pink-400',
    textSecondary: 'text-purple-300',
    border: 'border-pink-500',
    primary: 'bg-gradient-to-r from-cyan-400 to-pink-500',
    primaryHover: 'hover:from-cyan-500 hover:to-pink-600',
    accent: 'from-cyan-400 to-pink-500',
    gradient: 'bg-gradient-to-br from-pink-500 to-purple-900',
    shadow: 'shadow-2xl shadow-pink-500/50'
  },
  space: {
    name: 'Outer Space',
    bg: 'bg-gradient-to-br from-indigo-950 via-purple-950 to-black',
    card: 'bg-white/5 backdrop-blur-xl border border-white/20',
    cardHover: 'hover:bg-white/10',
    text: 'text-indigo-300',
    textSecondary: 'text-purple-300',
    border: 'border-white/20',
    primary: 'bg-gradient-to-r from-indigo-500 to-purple-500',
    primaryHover: 'hover:from-indigo-600 hover:to-purple-600',
    accent: 'from-indigo-500 to-purple-500',
    gradient: 'bg-gradient-to-br from-indigo-950 via-purple-950 to-black',
    shadow: 'shadow-2xl shadow-indigo-500/30'
  }
};

export const themeList = Object.keys(themes).map(key => ({
  id: key,
  name: themes[key].name
}));